name: Check Links

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.0

    - name: Check links with Lychee
      uses: lycheeverse/lychee-action@v2.5.0
      with:
        args: --config .github/workflows/lychee.toml --verbose --no-progress '*.md'
        fail: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
